"resources"
{
"maps/ff_summit_b1.lua" "file"
"materials/ff_summit/flat_normal.vtf" "file"
"materials/ff_summit/forestfloor2.vtf" "file"
"materials/ff_summit/forestfloor2_blendmod.vtf" "file"
"materials/ff_summit/forestfloorrockblend.vmt" "file"
"materials/ff_summit/rockleafblend.vmt" "file"
"materials/ff_summit/rockleafblendOld.vmt" "file"
"materials/ff_summit/shale.vmt" "file"
"materials/ff_summit/shale.vtf" "file"
"materials/ff_summit/shale_normal.vtf" "file"
"materials/models/cctrees/branches1024.vmt" "file"
"materials/models/cctrees/branches1024.vtf" "file"
"models/cctrees/tree1.dx80.vtx" "file"
"models/cctrees/tree1.dx90.vtx" "file"
"models/cctrees/tree1.mdl" "file"
"models/cctrees/tree1.phy" "file"
"models/cctrees/tree1.sw.vtx" "file"
"models/cctrees/tree1.vvd" "file"
}
